#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# controllers:
#     resource: ../src/Controller/Frontend
#     type:     annotation
#     prefix:   /panier

# # redirecting the homepage
# homepage:
#     path: /
#     controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
#     defaults:
#         path: /panier
#         permanent: true
